name: Android CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
      - name: BrowserStack Build and Upload
        uses: Joey-Fuentes/android-build-action@v1.0.0
        with:
          project-path: ui/espresso/BasicSample/
          output-path: my-app.apk
          browserstack-upload: true
          browserstack-username: ${{ secrets.BROWSERSTACK_USERNAME }}
          browserstack-access-key: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}
