name: Android Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
      - name: Build the test app
        working-directory: ui/espresso/BasicSample/
        run: ./gradlew assembleAndroidTest
      - name: Upload test APK
        uses: actions/upload-artifact@v1
        with:
          name: test-app
          path: ui/espresso/BasicSample/app/build/outputs/apk/androidTest/debug/app-debug-androidTest.apk
      - name: Build the app
        working-directory: ui/espresso/BasicSample/
        run: ./gradlew assembleDebug
      - name: Upload APK
        uses: actions/upload-artifact@v1
        with:
          name: app
          path: ui/espresso/BasicSample/app/build/outputs/apk/debug/app-debug.apk
      - name: BrowserStack Build and Upload
        uses: Joey-Fuentes/android-build-action@v1.0.0
        with:
          project-path: ui/espresso/BasicSample/
          output-path: my-app.apk
          browserstack-upload: true
          browserstack-username: ${{ secrets.BROWSERSTACK_USERNAME }}
          browserstack-access-key: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}
      - name: BrowserStack Run On-Target Tests
        env:
          USERNAME: ${{ secrets.BROWSERSTACK_USERNAME }}
          ACCESS_KEY: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}
        run: ./run-instrumented-tests.sh
