name: Android Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
      - name: Build the test app
        working-directory: ui/espresso/BasicSample/
        run: ./gradlew assembleAndroidTest
      - name: Upload test APK
        uses: actions/upload-artifact@v1
        with:
          name: test-app
          path: ui/espresso/BasicSample/app/build/outputs/apk/androidTest/debug/app-debug-androidTest.apk
      - name: Build the app
        working-directory: ui/espresso/BasicSample/
        run: ./gradlew assembleDebug
      - name: Upload APK
        uses: actions/upload-artifact@v1
        with:
          name: app
          path: ui/espresso/BasicSample/app/build/outputs/apk/debug/app-debug.apk
      - name: BrowserStack Build and Upload
        uses: Joey-Fuentes/android-build-action@v1.0.0
        with:
          project-path: ui/espresso/BasicSample/
          output-path: my-app.apk
          browserstack-upload: true
          browserstack-username: ${{ secrets.BROWSERSTACK_USERNAME }}
          browserstack-access-key: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}
      - name: BrowserStack Run On-Target Tests
        env:
          USERNAME: ${{ secrets.BROWSERSTACK_USERNAME }}
          ACCESS_KEY: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}
        run: |
          APP_URL=$(curl -u "env.USERNAME:env.ACCESS_KEY" -X POST "https://api-cloud.browserstack.com/app-automate/upload" -F "file=@./ui/espresso/BasicSample/app/build/outputs/apk/debug/app-debug.apk" | grep -Po '"app_url": *\K"[^"]*"' | sed 's/"//g')
          TEST_URL=$(curl -u "env.USERNAME:env.ACCESS_KEY" -X POST "https://api-cloud.browserstack.com/app-automate/espresso/test-suite" -F "file=@./ui/espresso/BasicSample/app/build/outputs/apk/androidTest/debug/app-debug-androidTest.apk" | grep -Po '"test_url": *\K"[^"]*"' | sed 's/"//g')
          BUILD_ID=$(curl -X POST "https://api-cloud.browserstack.com/app-automate/espresso/build" -d  "{\"devices\": [\"Google Pixel 3-9.0\"], \"app\": \"$APP_URL\", \"deviceLogs\" : true, \"testSuite\": \"$TEST_URL\"}" -H "Content-Type: application/json" -u "env.USERNAME:env.ACCESS_KEY" | grep -Po '"build_id": *\K"[^"]*"' | sed 's/"//g')
          sleep 60
          STATUS=$(curl -u "env.USERNAME:env.ACCESS_KEY" -X GET "https://api-cloud.browserstack.com/app-automate/espresso/v2/builds/$BUILD_ID" | grep -Po '"status": *\K"[^"]*"' | sed 's/"//g')
          STATUS=$(echo $STATUS | awk '{print $1}')
          if [ $STATUS == "passed" ]; then echo "On-target tests PASSED"; else exit 1; fi
          echo $STATUS
